# toml 大小写敏感
# toml 对缩进不敏感
# toml 字符串使用双引号包裹，内部可以使用转义字符
# toml 字面量字符串使用单引号包裹，内部不可以使用转义

[type]
    str1 = "周公瑾"
    str2 = """
    苟全乱世于性命\n
    不求闻达于诸侯\n
    """
    str3 = '诸葛亮'
    str4 = '''
    似是陋室\n
    惟吾德馨\n
    '''
    int1 = 100_000_000
    float1 = 3.1415926
    float2 = -2E-2
    float3 = 1e6
    bool1 = true
    date1 = 1979-05-27T07:32:00Z
    arr1 = [1, [1,2], [1,2,3], "guon", "show show way"]

