// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: shop.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fruit int32

const (
	Fruit_APPLE      Fruit = 0
	Fruit_ORANGE     Fruit = 1
	Fruit_BANANA     Fruit = 2
	Fruit_WATERMELON Fruit = 3
)

// Enum value maps for Fruit.
var (
	Fruit_name = map[int32]string{
		0: "APPLE",
		1: "ORANGE",
		2: "BANANA",
		3: "WATERMELON",
	}
	Fruit_value = map[string]int32{
		"APPLE":      0,
		"ORANGE":     1,
		"BANANA":     2,
		"WATERMELON": 3,
	}
)

func (x Fruit) Enum() *Fruit {
	p := new(Fruit)
	*p = x
	return p
}

func (x Fruit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Fruit) Descriptor() protoreflect.EnumDescriptor {
	return file_shop_proto_enumTypes[0].Descriptor()
}

func (Fruit) Type() protoreflect.EnumType {
	return &file_shop_proto_enumTypes[0]
}

func (x Fruit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Fruit.Descriptor instead.
func (Fruit) EnumDescriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{0}
}

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fruit Fruit `protobuf:"varint,1,opt,name=fruit,proto3,enum=Fruit" json:"fruit,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetFruit() Fruit {
	if x != nil {
		return x.Fruit
	}
	return Fruit_APPLE
}

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fruit Fruit `protobuf:"varint,1,opt,name=fruit,proto3,enum=Fruit" json:"fruit,omitempty"`
	Price int64 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{1}
}

func (x *Res) GetFruit() Fruit {
	if x != nil {
		return x.Fruit
	}
	return Fruit_APPLE
}

func (x *Res) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_shop_proto protoreflect.FileDescriptor

var file_shop_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x03,
	0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x05, 0x66, 0x72, 0x75, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x06, 0x2e, 0x46, 0x72, 0x75, 0x69, 0x74, 0x52, 0x05, 0x66, 0x72, 0x75, 0x69,
	0x74, 0x22, 0x39, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x66, 0x72, 0x75, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x06, 0x2e, 0x46, 0x72, 0x75, 0x69, 0x74, 0x52,
	0x05, 0x66, 0x72, 0x75, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2a, 0x3a, 0x0a, 0x05,
	0x46, 0x72, 0x75, 0x69, 0x74, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x50, 0x50, 0x4c, 0x45, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x42, 0x41, 0x4e, 0x41, 0x4e, 0x41, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x41, 0x54, 0x45,
	0x52, 0x4d, 0x45, 0x4c, 0x4f, 0x4e, 0x10, 0x03, 0x32, 0x29, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x04, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x04, 0x2e,
	0x52, 0x65, 0x73, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_shop_proto_rawDescOnce sync.Once
	file_shop_proto_rawDescData = file_shop_proto_rawDesc
)

func file_shop_proto_rawDescGZIP() []byte {
	file_shop_proto_rawDescOnce.Do(func() {
		file_shop_proto_rawDescData = protoimpl.X.CompressGZIP(file_shop_proto_rawDescData)
	})
	return file_shop_proto_rawDescData
}

var file_shop_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shop_proto_goTypes = []interface{}{
	(Fruit)(0),  // 0: Fruit
	(*Req)(nil), // 1: Req
	(*Res)(nil), // 2: Res
}
var file_shop_proto_depIdxs = []int32{
	0, // 0: Req.fruit:type_name -> Fruit
	0, // 1: Res.fruit:type_name -> Fruit
	1, // 2: GetPriceService.GetPrice:input_type -> Req
	2, // 3: GetPriceService.GetPrice:output_type -> Res
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shop_proto_init() }
func file_shop_proto_init() {
	if File_shop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shop_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_proto_goTypes,
		DependencyIndexes: file_shop_proto_depIdxs,
		EnumInfos:         file_shop_proto_enumTypes,
		MessageInfos:      file_shop_proto_msgTypes,
	}.Build()
	File_shop_proto = out.File
	file_shop_proto_rawDesc = nil
	file_shop_proto_goTypes = nil
	file_shop_proto_depIdxs = nil
}
