// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: shop.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetPriceServiceClient is the client API for GetPriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetPriceServiceClient interface {
	GetPrice(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type getPriceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetPriceServiceClient(cc grpc.ClientConnInterface) GetPriceServiceClient {
	return &getPriceServiceClient{cc}
}

func (c *getPriceServiceClient) GetPrice(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/GetPriceService/GetPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetPriceServiceServer is the server API for GetPriceService service.
// All implementations must embed UnimplementedGetPriceServiceServer
// for forward compatibility
type GetPriceServiceServer interface {
	GetPrice(context.Context, *Req) (*Res, error)
	mustEmbedUnimplementedGetPriceServiceServer()
}

// UnimplementedGetPriceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGetPriceServiceServer struct {
}

func (UnimplementedGetPriceServiceServer) GetPrice(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (UnimplementedGetPriceServiceServer) mustEmbedUnimplementedGetPriceServiceServer() {}

// UnsafeGetPriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetPriceServiceServer will
// result in compilation errors.
type UnsafeGetPriceServiceServer interface {
	mustEmbedUnimplementedGetPriceServiceServer()
}

func RegisterGetPriceServiceServer(s grpc.ServiceRegistrar, srv GetPriceServiceServer) {
	s.RegisterService(&GetPriceService_ServiceDesc, srv)
}

func _GetPriceService_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetPriceServiceServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GetPriceService/GetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetPriceServiceServer).GetPrice(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// GetPriceService_ServiceDesc is the grpc.ServiceDesc for GetPriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetPriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetPriceService",
	HandlerType: (*GetPriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrice",
			Handler:    _GetPriceService_GetPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop.proto",
}
